FROM ubuntu:18.04

RUN apt-get update && apt-get install -y openssl g++ wget curl libssl1.0-dev
RUN apt-get install -y nodejs-dev node-gyp libssl1.0-dev npm

ENV DAPPER_SOURCE /source
ENV DAPPER_OUTPUT build
# ENV DAPPER_CP poco-1.7.4-all.tar.gz scripts

WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]