#!/bin/bash

BUILDDIR="$DAPPER_SOURCE/$DAPPER_OUTPUT"
LODDIR="$DAPPER_SOURCE/core/build"

mkdir -p "$BUILDDIR"/opt
cp -a "$LODDIR"/instdir "$BUILDDIR"/opt/libreoffice
cp -a "$LODDIR"/instdir /opt/libreoffice

# cp -a "$DAPPER_SOURCE"/poco/build "$BUILDDIR"/opt/poco
# cp -a "$DAPPER_SOURCE"/poco/build /opt/poco

# build
( cd online/source && ./autogen.sh ) || exit 1
( cd online/source && ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-silent-rules --with-lokit-path="$LODDIR"/include --with-lo-path=/opt/libreoffice --with-poco-includes="$DAPPER_SOURCE"/poco/build/include --with-poco-libs="$DAPPER_SOURCE"/poco/build/lib $ONLINE_EXTRA_BUILD_OPTIONS) || exit 1
( cd online/source && scripts/locorestrings.py "$DAPPER_SOURCE"/online/source "$DAPPER_SOURCE"/core/core/translations )
( cd online/source && scripts/unocommands.py --update "$DAPPER_SOURCE"/online/source "$DAPPER_SOURCE"/core/core )
( cd online/source && scripts/unocommands.py --translate "$DAPPER_SOURCE"/online/source "$DAPPER_SOURCE"/core/core/translations )
( cd online/source && make -j 8) || exit 1

# copy stuff
( cd online/source && DESTDIR="$BUILDDIR" make install ) || exit 1
