#!/bin/bash

cd source
./autogen.sh --with-distro=LibreOfficeOnline
make build-nocheck

mkdir -p $DAPPER_OUTPUT
cp -a instdir/ $DAPPER_OUTPUT
cp -a include/ $DAPPER_OUTPUT
cp -a translations/ $DAPPER_OUTPUT